name: tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        run: |
          python -m pip install uv
          uv venv
      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          which python
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install dependencies
        run:  |
          git submodule update --init --recursive
          uv pip install -e ".[dev, docs, all, example]"
      - name: Run tests with pytest
        run: /home/runner/work/DACBench/DACBench/.venv/bin/python -m pytest tests
